name: clone-templates

on:
  push:
    paths:
      - templates.txt
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  sync:
    if: github.event_name != 'push' || github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sync templates
        run: ./scripts/sync_templates.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -d vendor ]; then
            git add vendor
          fi
          git add .gitmodules codex.json templates.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update templates"
            git push
          fi

      - name: Trigger clone-vendors via API
        if: always()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/clone-vendors.yml/dispatches \
            -d '{"ref":"${{ github.ref_name }}"}'
