name: publish

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: false

      - name: Prepare published branch
        run: |
          set -x
          git checkout -B published
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "::group::Before cleanup"
          ls -al
          git submodule status || true
          echo "::endgroup::"
          git submodule deinit -f --all || true
          rm -rf vendor template apps.json DEV_INSTRUCTIONS.md vendors.txt vendor_profiles
          rm -rf frappe_app_template erpnext_app_template template_frappe template_erpnext || true
          find . -maxdepth 1 -type d -name '*_app_template*' -exec rm -rf {} + || true
          if [ -f .gitmodules ]; then
            git config -f .gitmodules --get-regexp path | awk '{print $2}' | xargs -r rm -rf
          fi
          rm -rf .git/modules
          find . -name '.git*' -not -name '.git' -exec rm -rf {} +
          find . -mindepth 1 -maxdepth 1 ! -name 'app' ! -name '.git' -exec rm -rf {} +
          if [ -d app ]; then
            shopt -s dotglob
            mv app/* .
            rmdir app
            shopt -u dotglob
          fi
          echo "::group::After cleanup"
          ls -al
          echo "::endgroup::"
          git add -A
          git commit -m "chore: publish"
          git push -f origin published
